CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    NAME VARCHAR (100) NOT NULL,
    EMAIL VARCHAR (100) NOT NULL,
    PASSWORD VARCHAR (100) NOT NULL,
    TYPE VARCHAR(10) NOT NULL CHECK (TYPE IN ('ADMIN', 'CLIENTE'))

);


MERGE INTO CUSTOMER (ID, NAME, EMAIL, PASSWORD, TYPE)
    KEY (EMAIL)
    VALUES (RANDOM_UUID(), 'admin', 'admin@gmail.com', 'admin', 'ADMIN');



CREATE TABLE IF NOT EXISTS ADDRESS (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    CEP VARCHAR(20) NOT NULL,
    STREET VARCHAR(150) NOT NULL,
    NEIGHBORHOOD VARCHAR(55) NOT NULL,
    CUSTOMER_ID UUID,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);





